-- Top 5 Customers by Revenue:
-- Business Question: Who are the top 5 customers generating the highest total revenue from completed orders?
SELECT 
    users.user_id,
    users.name,
    SUM(orders.total_amount) AS total_revenue
FROM orders
INNER JOIN users
    ON users.user_id = orders.user_id
WHERE order_status = 'completed'
GROUP BY users.user_id, users.name
ORDER BY total_revenue DESC
LIMIT 5;


-- Customer Classification:
-- Business Question: How many customers are one-time buyers versus repeat buyers based on completed orders?
SELECT
    customer_type,
    COUNT(*) AS customer_count
FROM (
    SELECT
        user_id,
        CASE 
            WHEN COUNT(order_id) = 1 THEN 'one_time'
            ELSE 'repeat'
        END AS customer_type
    FROM orders
    WHERE order_status = 'completed'
    GROUP BY user_id
) sub
GROUP BY customer_type;

-- Revenue Contribution by Customer Type:
-- Business Question: How much revenue is generated by repeat customers compared to one-time customers?

WITH customer_orders AS (
    SELECT
        user_id,
        COUNT(order_id) AS total_orders,
        SUM(total_amount) AS total_revenue
    FROM orders
    WHERE order_status = 'completed'
    GROUP BY user_id
),

customer_classification AS (
    SELECT
        user_id,
        total_revenue,
        CASE 
            WHEN total_orders = 1 THEN 'one_time'
            ELSE 'repeat'
        END AS customer_type
    FROM customer_orders
)

SELECT
    customer_type,
    COUNT(*) AS customer_count,
    SUM(total_revenue) AS total_revenue,
    ROUND(
        SUM(total_revenue) * 100.0 /
        (SELECT SUM(total_revenue) FROM customer_classification),
        2
    ) AS revenue_percentage
FROM customer_classification
GROUP BY customer_type;


