

-- Total Revenue:
-- Business Question: What is the total revenue from completed orders?

SELECT SUM(total_amount) AS total_revenue
FROM orders
WHERE order_status = 'completed';


-- Monthly Revenue Trend: 
-- Business Question: How does revenue change month over month?

SELECT 
    DATE_TRUNC('month', order_date) AS month,
    SUM(total_amount) AS monthly_revenue
FROM orders
WHERE order_status = 'completed'
GROUP BY month
ORDER BY month;


-- Revenue Concentration (Top 10% Customers):
-- Business Question: What percentage of total revenue is generated by the top 10% of customers?

WITH customer_revenue AS (
    SELECT 
        user_id,
        SUM(total_amount) AS revenue
    FROM orders
    WHERE order_status = 'completed'
    GROUP BY user_id
),

customer_count AS (
    SELECT COUNT(*) AS total_customers
    FROM customer_revenue
),

top_customers AS (
    SELECT *
    FROM customer_revenue
    ORDER BY revenue DESC
    LIMIT (
        SELECT CEIL(total_customers * 0.10)
        FROM customer_count
    )
),

total_revenue AS (
    SELECT SUM(revenue) AS overall_revenue
    FROM customer_revenue
)

SELECT 
    ROUND(
        (SELECT SUM(revenue) FROM top_customers) * 100.0 /
        (SELECT overall_revenue FROM total_revenue),
        2
    ) AS top_10_percent_revenue_share;
